#  RMIT University Vietnam
#  Course: COSC2767 Systems Deployment and Operations
#  Semester: 2024C
#  Assessment: Assignment 2
#  Author: Le Dinh Ngoc Quynh
#  ID: s3791159
#  Created  date: 10 Jan 2025
#  Last modified: 10 Jan 2025
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: fe-health-check
spec:
  metrics:
    - name: test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: check-fe-svc
                    image: curlimages/curl:latest
                    command:
                      - sh
                      - -c
                    args:
                      - |
                        URL=http://fe-svc-staging.production.svc.cluster.local
                        STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://fe-svc-staging.production.svc.cluster.local);
                        echo $STATUS;
                        
                        if [ $STATUS -eq 200 ]; then
                            echo "PASS: HTTP status code is 200"
                        else
                            echo "FAIL: HTTP status code is not 200"
                            exit 1
                        fi
                        
                        CONTENT=$(curl -s $URL)
                        echo $CONTENT
                        if echo "$CONTENT" | grep -q '<div id="root">'; then
                            echo "PASS: React root element is present"
                        else
                            echo "FAIL: React root element is missing"
                            exit 1
                        fi
                        
                        if echo "$CONTENT" | grep -q '<title>RMIT Store</title>'; then
                            echo "PASS: React title element is present"
                        else
                            echo "FAIL: React title element is missing"
                            exit 1
                        fi

                restartPolicy: Never
