#  RMIT University Vietnam
#  Course: COSC2767 Systems Deployment and Operations
#  Semester: 2024C
#  Assessment: Assignment 2
#  Author: Le Dinh Ngoc Quynh
#  ID: s3791159
#  Created  date: 10 Jan 2025
#  Last modified: 10 Jan 2025
apiVersion: v1
kind: Service
metadata:
  name: fe-svc-staging
  labels:
    app: fe
spec:
  selector:
    app: fe
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
